# Generated by Django 3.2.9 on 2021-11-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='body',
            new_name='description',
        ),
        migrations.AddField(
            model_name='snippet',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='snippet',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='snippet',
            name='sample_type',
            field=models.CharField(choices=[('sediment', 'Sediment'), ('water', 'Water')], default='water', max_length=100),
            preserve_default=False,
        ),
    ]
