# Generated by Django 3.2.9 on 2021-11-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_snippet_sample_cleanup'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='analysis_instrumentation',
            field=models.CharField(blank=True, choices=[('gc/ms', 'GC/MS'), ('gc/fid', 'GC/FID'), ('spectrophotometer', 'Spectrophotometer'), ('iatroscan', 'Iatroscan'), ('lc', 'LC'), ('none', 'None')], max_length=100),
        ),
        migrations.AddField(
            model_name='snippet',
            name='testingthis',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
