# Generated by Django 3.2.9 on 2021-11-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20211119_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='testingthis',
        ),
        migrations.AddField(
            model_name='snippet',
            name='analysis_pah',
            field=models.BooleanField(default=False),
        ),
    ]
