# Generated by Django 3.2.9 on 2021-11-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20211119_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='analysis_alkanes',
            field=models.BooleanField(default=False),
        ),
    ]
