# Generated by Django 3.2.9 on 2021-11-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_snippet_analysis_alkanes'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='analysis_btex',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='snippet',
            name='analysis_phenols',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='snippet',
            name='analysis_tph',
            field=models.BooleanField(default=False),
        ),
    ]
