# Generated by Django 3.2.9 on 2021-11-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20211119_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='log_comments',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
